### ISSUE TITLE
Chrono support

### ISSUE THREAD

**Issue by xoac** [tailhook/serde-millis#2]
It would be nice if that crate could support [chrono](https://docs.rs/chrono/0.4.0/chrono/index.html) as feature. 

or the option to allow implement Milliseconds trait for own types. As far as I understand now it's impossible due to [Sealed](https://github.com/tailhook/serde-millis/blob/master/src/traits.rs#L5) that is not public outside crate.

**Comment by tailhook** [comment]
Would be fine if made feature-gated. Do you want to make PR?

**Comment by xoac** [comment]
Can u assign it to me? I can try, but I don't have time to begin od August. And there is a change I will forget abut it.
