### ISSUE TITLE
split out milliseconds as separate crate  

### ISSUE THREAD

**Issue by dzmitry-lahoda** [tailhook/serde-millis#5]
may be make serde feature.

i have 3 projects in rust (backend, p2p, game area) - all need unix millis, have to drag code for them. for sure nice to have serde

**Comment by tailhook** [comment]
This crate specifically about (de)serialihizing Duration and Instant and milliseconds. So I'm not sure what do you want to have to move to a separate crate. 

If you're saying that this has to be merged into `tserde` itself. I don't think this is going to happen, as this is still only one of the ways to serialize these things. Putting all of them into a `serde` crate will make it huge uber crate that is not only big in size but also slow to compile and hard to configure. But you should ask in the serde crate issue tracker for that.

**Comment by dzmitry-lahoda** [comment]
now_milliseconds is main crate, while serde its feature. so i can use package to have millis out of now, and optionally serde for it

**Comment by tailhook** [comment]
Converting `Instant` to milliseconds is `instant.duration_since(UNIX_TIMESTAMP).unwrap().as_millis()`. This is annoying but I wouldn't use a dependency just for this task. A function in a project is good enough. And in my use cases I prefer to use Rust native types in the app itself and only convert on the boundary (which is serialization) so this crate works just fine for me.
